name: C++ Lint and Format Check
on:
  push:
    branches:
      - '*'
    paths:
      - '**.cc'
      - '**.h'
  pull_request:
    branches:
      - main
      - development
    paths:
      - '**.cc'
      - '**.h'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ClangFormat
        run: sudo apt-get install clang-format

      - name: Set up Clang-Tidy
        run: sudo apt-get install clang-tidy

      - name: Run ClangFormat
        run: clang-format -i --style=file *.cc *.h
        working-directory: ${{ github.workspace }}

      - name: Run Clang-Tidy
        run: clang-tidy *.cc -- -std=c++17
        working-directory: ${{ github.workspace }}
