name: Unit tests

on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - main
        - development
      paths:
        - '**.cc'
        - '**.h'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download, configure and install gtest
      run: |
        wget https://github.com/google/googletest/archive/release-1.10.0.tar.gz
        tar xf release-1.10.0.tar.gz
        cd googletest-release-1.10.0
        cmake -DBUILD_SHARED_LIBS=OFF .
        sudo make install
    
    - name: Creating directories
      run: mkdir -p build bin

    - name: Build project
      run: make build

    - name: Run unit tests
      run: make test
