name: Unit tests

on:
    push:
      branches:
        - '*'
    pull_request:
      branches:
        - main
        - development
      paths:
        - '**.cc'
        - '**.h'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: actions/setup-cmake@v1

